query ProductCategoryMember {
  productCategory {
    productCategoryId
    primaryParentCategoryId
    categoryName
  }
  productCategoryMember {
    productCategoryId
    productId
    product {
      productName
    }
    fromDate
    thruDate
    comments
    sequenceNum
    quantity
  }
}

query ProductFeatureIactn($productId: String) {
  productFeatureIactnType{
    productFeatureIactnTypeId
    parentTypeId
    description
  }
  productFeature{
    productFeatureId
    description
  }
  productFeatureIactn(productId: $productId){
    productFeatureId
    productFeature{
      description
    }
    productFeatureIdTo
    productFeatureTo{
      description
    }
    productFeatureIactnTypeId
    productFeatureIactnType{
      description
    }
  }
}

query ProductFeatureAppl($productId: String) {
  productFeatureApplType{
    productFeatureApplTypeId
    parentTypeId
    description
  }
  productFeature{
    productFeatureId
    description
  }
  productFeatureAppl(productId: $productId){
    productFeatureId
    productFeature{
      description
    }
    productFeatureApplTypeId
    productFeatureApplType{
      description
    }
    fromDate
    thruDate
    sequenceNum
    amount
  }
}