query ProductCategoryMember {
  productCategory {
    productCategoryId
    primaryParentCategoryId
    categoryName
  }
  productCategoryMember {
    productCategory{
      productCategoryId
    }
    product {
      productId
      productName
    }
    fromDate
    thruDate
    comments
    sequenceNum
    quantity
  }
}

query ProductFeatureIactn($productId: String) {
  productFeatureIactnType{
    productFeatureIactnTypeId
    parentTypeId
    description
  }
  productFeature{
    productFeatureId
    description
  }
  productFeatureIactn(productId: $productId){
    productFeature{
      productFeatureId
      description
    }
    productFeatureTo{
      productFeatureId
      description
    }
    productFeatureIactnType{
      productFeatureIactnTypeId
      description
    }
  }
}

query ProductFeatureAppl($productId: String) {
  productFeatureApplType{
    productFeatureApplTypeId
    parentTypeId
    description
  }
  productFeature{
    productFeatureId
    description
  }
  productFeatureAppl(productId: $productId){
    productFeature{
      productFeatureId
      description
    }
    productFeatureApplType{
      productFeatureApplTypeId
      description
    }
    fromDate
    thruDate
    sequenceNum
    amount
  }
}